spring.datasource.url=jdbc:mysql://localhost:3306/comunicacao_db
spring.datasource.username=developer
spring.datasource.password=1234567
spring.jpa.hibernate.ddl-auto=create

spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL57Dialect
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
server.port = 1450

notificacao.url=localhost:1920/email
usuarios.url=localhost:1974/usuario

cron.horario=0 0/5 * * * ?

usuario.email = daniel.yassuo.rodrigues@gmail.com
usuario.senha = Seropri@1